# These are supported funding model platforms

github: risetogethercommunity
patreon: risetogethercommunity
open_collective: rise-together
thanks_dev: logicbyroshan
custom: ['https://www.risetogether.tech/']
